name: CI/CD Pipeline for ${{ values.app_name }}
on:
    push:
        branches:
            - main
        paths:
            - src/**

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            -   name: Login to Docker hub
                uses: docker/login-action@v3
                with:
                    username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}
                    password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}

            -   name: Shorten commit_id
                shell: bash
                run: |
                    echo "COMMIT_ID=${GITHUB_SHA::6}" >> ${GITHUB_ENV}
            
            -   name: Docker Build and Push
                uses: docker/build-push-action@v6
                with:
                    push: true
                    tags: aumthakkar/${{ values.app_name }}:${{ '${{ env.COMMIT_ID }}' }}

        outputs:
            commit_id: ${{ '${{ env.COMMIT_ID }}' }}

    cd:
        runs-on: self-hosted
        needs: ci
        steps:
            -   name: Checkout Github Repo
                uses: actions/checkout@v6

            - name: Update tag in values.yaml
              run: |
                sudo apt update && sudo apt install python3-pip -y
                pip install yq --break-system-packages
                echo ${{ '${{ needs.ci.outputs.commit_id }}' }}
                yq -Yi '.image.tag = "${{ '${{ needs.ci.outputs.commit_id }}' }}"' charts/${{ values.app_name }}/values-${{ values.app_env }}.yaml

            -   name: Commit Change
                uses: EndBug/add-and-commit@v9
                with:
                    message: "pushed the image with tag: ${{ '${{ needs.ci.outputs.commit_id }}' }}"

            -   name: Install ArgoCD CLI
                run: |
                    curl -ksSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/v3.2.2/argocd-linux-amd64
                    sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
                    sudo chmod +x /usr/local/bin/argocd

            -   name: ArgoCD login 
                run: |
                    argocd login argocd-server.argocd \
                    --grpc-web \
                    --insecure \
                    --username ${{ '${{ secrets.ARGOCD_USERNAME }}' }} \
                    --password ${{ '${{ secrets.ARGOCD_PASSWORD }}' }}

            -   name: ArgoCD Repo Create and Sync
                run: |
                    REPO="https://github.com/aum-thakkar/${{ values.app_name }}.git"
                    argocd repo list ${REPO} | grep ${REPO} || argocd repo add ${REPO}

                    if argocd get app ${{ values.app_name }} >/dev/null 2>&1; then
                        echo "Deleting app: ${{ values.app_name }}"
                        argocd app delete ${{ values.app_name }} --cascade --yes
                        
                        echo "Waiting for the app to completely delete..."
                        while argocd get app ${{ values.app_name }} >/dev/null 2>&1; do
                            sleep 5
                        done
                    fi
                    
                    argocd app create ${{ values.app_name }} \
                    --dest-namespace ${{ values.app_env }} \
                    --dest-server https://kubernetes.default.svc \
                    --path charts/${{ values.app_name }} \
                    --repo ${REPO} \
                    --revision main \
                    --sync-option CreateNamespace=true \
                    --sync-policy manual \
                    --values values-${{values.app_env}}.yaml

                    argocd app sync ${{ values.app_name }}
                    argocd app wait ${{ values.app_name }} --timeout 120







                

